flask_app/functions/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_required
from mongoengine.queryset.visitor import Q
from datetime import datetime
import json
from flask_app.utils_nodb import FormField

from ..forms import MemberSearchForm, LoadFormObject
from ..models import User, FormObject, FormSubmission
from ..utils import get_b64_img
from ..utils_nodb import date_str, now
# get calendar api route methods
from ..calendar.routes import getEvents

functions = Blueprint("functions", __name__)

""" ************ View functions ************ """


@functions.route("/", methods=["GET"])
def index():
    return render_template("index.html")

@functions.route("/about", methods=["GET"])
def about():
    return render_template("about.html")

@functions.route("/members", methods=["GET", "POST"])
@login_required
def members():
    form = MemberSearchForm()

    if form.validate_on_submit():
        query = form.query.data
        return redirect(url_for("functions.members", query=query))
    
    # check for GET arg
    query = request.args.get('query')
    if(query):
        users = User.objects(Q(fname__icontains=query) | Q(lname__icontains=query))
    else:
        users = User.objects()
    for user in users:
        user.img = get_b64_img(user.uid)
    return render_template("members.html", users=users, form=form, query=query)

@functions.route("/forms", methods=["GET"])
@login_required
def forms():
    c_forms = FormSubmission.objects(user=current_user).only('uuid', 'form', 'completed_dt').order_by('-completed_dt')
    completed_ids = [form.form.uuid for form in c_forms]
    u_forms = FormObject.objects(uuid__nin=completed_ids).order_by('+due_by')
    # add is_late to each form
    for form in u_forms:
        form.is_late = (now() > form.due_by)
        form.due_by = date_str(form.due_by)
    for sub in c_forms:
        sub.is_late = (sub.completed_dt > sub.form.due_by)
        sub.completed_dt = date_str(sub.completed_dt)
    return render_template("forms.html", u_forms=u_forms, c_forms=c_forms)

@functions.route("/viewForm", methods=["GET", "POST"])
@login_required
def viewForm():
    # check ID was passed
    if request.args.get('id') == None:
        flash("No form ID provided!")
        return redirect(url_for('functions.forms'))
    uuid = request.args.get('id')
    form_obj = FormObject.objects(uuid=uuid).first()
    if form_obj:
        # first check if they already completed it
        if FormSubmission.objects(user=current_user, form=form_obj).first():
            flash('Form already completed!')
            return redirect(url_for('functions.forms'))
        # now, construct custom form
        form = LoadFormObject(form_obj)

        # since form only exists here we check for POST here
        if form.validate_on_submit():
            # convert submission into strings, cut off submit/csrf
            data = [str(i) for i in list(form.data.values())[:-2]]
            submission = FormSubmission(user=current_user, form=FormObject.objects(uuid=uuid).first(), data=data, completed_dt=now())
            submission.save()
            flash("Successfully submitted form!")
            return redirect(url_for('functions.forms'))
        elif form.errors:
            flash(form.errors)

        return render_template("form_complete.html", name=form_obj.name, form=form)
    else:
        flash("Form not found")
        return redirect(url_for('functions.forms'))

# ***** EVENTS ROUTES *****
@functions.route("/events", methods=["GET"])
@login_required
def events():
    events = json.loads(getEvents().data)
    new_events = []
    for event in events:
        new_event = {}
        new_event['title'] = event.get('summary')
        new_event['description'] = event.get('description', 'No Description')
        new_event['start'] = date_str(datetime.strptime(event.get('start',{}).get('dateTime')[:-6], "%Y-%m-%dT%H:%M:%S"))
        form_id = FormObject.objects(event_id=event.get('id')).first()
        if form_id:
            new_event['form_link'] = f"/viewForm?id={form_id['uuid']}"
        new_events.append(new_event)
    return render_template("events.html", events=new_events)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.utils import secure_filename
from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateProfilePicForm, UpdateAccountForm, ResetPasswordForm
from ..models import PointLog, User
from ..utils import get_status, get_points, get_b64_img

users = Blueprint("users", __name__)

""" ************ User Management views ************ """

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("functions.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        # create user
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(
            uid=form.uid.data, 
            email=form.email.data, 
            phone=form.phone.data,
            password=hashed,
            fname=form.fname.data,
            lname=form.lname.data,
            isAdmin=False
        )
        user.save()
        # create initial points at 100
        points = PointLog(
            user=user,
            points=100,
            reason="Initial Points"
        )
        points.save()
        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("functions.index"))

    form = LoginForm()
    print(list(form))
    if form.validate_on_submit():
        user = User.objects(uid=form.uid.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("functions.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    uform = UpdateAccountForm()
    pform = UpdateProfilePicForm()
    rform = ResetPasswordForm()

    if uform.validate_on_submit():
        current_user.modify(
            email=uform.email.data,
            phone=uform.phone.data,
            fname=uform.fname.data,
            lname=uform.lname.data
        )
        current_user.save()
        return redirect(url_for("users.account"))
    
    if pform.validate_on_submit():
        img = pform.pfp.data
        filename = secure_filename(img.filename)
        content_type = f'images/{filename[-3:]}'
        if current_user.profile_pic.get() is None:
            current_user.profile_pic.put(img.stream, content_type=content_type)
        else:
            current_user.profile_pic.replace(img.stream, content_type=content_type)
        current_user.save()
        return redirect(url_for('users.account'))

    if rform.validate_on_submit():
        hashed = bcrypt.generate_password_hash(rform.password.data).decode("utf-8")
        current_user.modify(password=hashed)
        current_user.save()
        return redirect(url_for("users.account"))

    # pre-populate form
    uform.email.data = current_user.email
    uform.phone.data = current_user.phone
    uform.fname.data = current_user.fname
    uform.lname.data = current_user.lname

    points = get_points(current_user)
    log = PointLog.objects(user=current_user).order_by('-date')
    return render_template(
        "account.html",
        title="Account",
        points=points,
        log=log,
        status=get_status(points),
        uform=uform,
        pform=pform,
        rform=rform,
        image=get_b64_img(current_user.uid)
    )

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}

<div class="container mt-4">
    <h1>About this Project</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col-8 mx-auto mt-2">
            <h4>Group Members:</h4>
            <ul><li>Christian Tonti</li></ul>
            <br/>
            <h4>About:</h4>
            <p>This project serves as a member portal for any sort of organization that 
                tries to keep members participating through the use of a points system.
                Largely inspired by my fraternity (hence the name), it includes not only
                point tracking, but also event creation onto a Google Calendar, the creation
                and completion of custom forms, basic account management functions such as
                profile pictures, and a member info lookup page.
                <br/>
                One small note is that a user must be manually elevated to Admin role in the database,
                as this is the only secure way I could think about doing so.
            </p>
        </div>
    </div>
</div>

{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        {% if image %}
        <div class="col-2 text-center">
            <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
        </div>
        {% endif %}
        <div class="col-10">
            <h1>Hey, {{ current_user.fname }}!</h1>
            <h4>Current Points: {{ points }}</h4>
            <p>Status: <span class="{{ status.style }}">{{ status.text }}</span></p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h4>Points Log:</h4>
            <table class="table table-striped table-bordered" id="pointsTable">
                <tr>
                    <th>Date</th>
                    <th>Point Change</th>
                    <th>Reason</th>
                </tr>
                {% for item in log %}
                    <tr>
                        <td>{{ item.date }}</td>
                        <td>{{ item.points }}</td>
                        <td>{{ item.reason }}</td>
                    </tr>    
                {% endfor %}
            </table>
        </div>    
    </div>
    <div class="row">
        <div class="col-6">
            <h4>Update Account Info</h4>
            <form action="" method="POST">
                {{ uform.csrf_token }}
                <div class="form-group mb-3">
                    {{ uform.email.label(class="form-control-label") }}
                    {{ uform.email(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ uform.phone.label(class="form-control-label") }}
                    {{ uform.phone(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ uform.fname.label(class="form-control-label") }}
                    {{ uform.fname(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ uform.lname.label(class="form-control-label") }}
                    {{ uform.lname(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ uform.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
        <div class="col-6">
            <h4>Update Profile Photo</h4>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ pform.csrf_token }}
                <div class="form-group mb-3">
                    {{ pform.pfp.label }}
                    {{ pform.pfp(class="form-control") }}
                    {% for error in pform.pfp.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group mb-3">
                    {{ pform.submit(class="btn btn-primary") }}
                </div>
            </form>
            <h4>Reset Password</h4>
            <form action="" method="POST">
                {{ rform.csrf_token }}
                <div class="form-group mb-3">
                    {{ rform.password.label(class="form-control-label") }}
                    {{ rform.password(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ rform.confirm_password.label(class="form-control-label") }}
                    {{ rform.confirm_password(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ rform.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>KTPortal</title>
    {% endif %}
</head>
<body>
    <!-- Moved to top so I can have inline scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    </body>
</html>

flask_app/templates/event_creation.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <h1>Event Creation</h1>
    <small class="mb-3"><b>NOTE: Event Creation is very limited in functionality.
         If you want to edit or remove an event, please do so on the Google Calendar</b></small>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col">    
            <form action="" method="post">
                {{ form.csrf_token }}
                <div class="form-group mb-3">
                    {{ form.name.label(class="form-control-label") }}
                    {{ form.name(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.description.label(class="form-control-label") }}
                    {{ form.description(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.start.label(class="form-control-label") }}
                    {{ form.start(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.end.label(class="form-control-label") }}
                    {{ form.end(class="form-control") }}
                </div>
                <div class="form-check px-0 mb-3">
                    {{ form.create_form.label(class="form-check-label") }}
                    {{ form.create_form(class="form-check") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}>

flask_app/templates/events.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <h1>Event Calendar</h1>
    <div class="row">
        <div class="col-8">
            <iframe id="calendarFrame" src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FNew_York&showTitle=0&showCalendars=0&showTabs=1&showPrint=1&src=amgyZTA4aGM3OGhxYnNtcDRjdHJvanVnMm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%23F09300" style="border:solid 1px #777" height="500" frameborder="0" scrolling="no"></iframe>
        </div>
        <div class="col-4">
            <h3>Upcoming Events</h3>
            {% if events %}
                <ul>
                    {% for event in events %}
                    <li>
                        {{event.title}} - {{event.start}}
                        <ul>
                            <li>{{event.description}}</li>
                            {% if event.form_link %}
                                <li><a href='{{event.form_link}}'>Attendance Form</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No events found.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}>

flask_app/templates/form_complete.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <h1>Form: {{ name }}</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col">    
            {% if form %}
                <form action="" method="post">
                    {{ form.csrf_token }}
                    {% for field in form %}
                        {% if field.type not in ('SubmitField', 'CSRFTokenField') %}
                            {% if field.type == 'BooleanField' %}
                                <div class="form-check mb-3 px-0">
                                    {{ field.label(class="form-check-label") }}
                                    {{ field(class="form-check") }}
                                </div>
                            {% else %}
                                <div class="form-group mb-3">
                                    {{ field.label(class="form-control-label") }}
                                    {{ field(class="form-control") }}
                                </div>
                            {% endif %}
                        
                        {% endif %}
                    {% endfor %}
                    <div class="form-group mb-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}>

flask_app/templates/form_creation.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <h1>Form Management</h1>
    <small class="mb-3"><b>NOTE: Form Creation is very limited in functionality.
         Input validation on user-created forms does not exist beyond type checking.
          Additionally, forms cannot be modified, only deleted &mdash; so create them carefully!</b></small>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col">    
            {% if form %}
                <form action="" method="post">
                    {{ form.csrf_token }}
                    {% for field in form %}
                        {% if field.type not in ('SubmitField', 'CSRFTokenField') %}
                        <div class="form-group mb-3">
                            {{ field.label(class="form-control-label") }}
                            {{ field(class="form-control", id="memberSelect") }}
                        </div>
                        {% endif %}
                    {% endfor %}
                    <div class="form-group mb-3">
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            {% else %}
                <div class="row mt-3">
                    <h3>Form Creation</h3>
                    <form action="" method="get">
                        <div class="form-group mb-3">
                            <label class="form-control-label" for="num_fields">To create a form, first select the number of fields to create:</label>
                            <input class="form-control" id="num_fields" max="10" min="1" name="num_fields" required="" type="number" value="2">
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" id="submit" name="submit" type="submit" value="Submit">
                        </div>
                    </form>
                </div>
                <div class="row mt-3">
                    <h3>Existing Forms</h3>
                    {% if all_forms %}
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Due Date</th>
                                    <th>Submissions</th>
                                    <th>Remove?</th>
                                </tr>
                            </thead>
                            <tbody id="formsTable">
                                {% for form in all_forms %}
                                    <tr>
                                        <td>{{ form.name }}</td>
                                        <td>{{ form.due_by }}</td>
                                        <td><a href="/viewSubmissions?id={{form.uuid}}" class="btn btn-primary">Go &rarr;</a></td>
                                        <td><a href="/formRemove?id={{form.uuid}}" class="btn btn-close"></a></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>No user-created forms found.</p>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3" id="mainNavbar">
    <a class="navbar-brand" href="{{ url_for('functions.index') }}">KTPortal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('functions.index') }}">Home</a>
            </li>
            {% if current_user.is_authenticated %}
                <!-- user links here -->
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('functions.forms') }}">Forms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('functions.events') }}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('functions.members') }}">Members</a>
                </li>
                {% if current_user.is_admin() %}
                    <!-- admin links here -->
                    <li class="nav-item border-end mx-2"></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.points') }}">Points</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.formCreate') }}">Form Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.eventCreate') }}">Event Creation</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('functions.about') }}">About</a>
            </li>
            {% if current_user.is_authenticated %}
                <a class="btn btn-secondary" href="{{ url_for('users.account') }}">Account</a>
                <a class="btn btn-secondary mx-2" href="{{ url_for('users.logout') }}">Log Out</a>
            {% else %}
                <a class="btn btn-secondary" href="{{ url_for('users.login') }}">Log In</a>
            {% endif %}
        </li>              
    </ul>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="container mt-4">
    <h1>Welcome to the Kappa Theta Pi Member Portal!</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col-8 mx-auto mt-2">
            <div id="homepageCarousel" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#homepageCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#homepageCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#homepageCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" src="{{ url_for('static', filename='carousel1.jpg') }}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{{ url_for('static', filename='carousel2.jpg') }}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" src="{{ url_for('static', filename='carousel3.jpg') }}" alt="Third slide">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#homepageCarousel" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#homepageCarousel" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
            </div>
        </div>
    </div>
    <div class="row pt-4">
        <div class="col-6 px-4">
            <h3>About Us:</h3>
            <p>Kappa Theta Pi, Epsilon Chapter is the University of Maryland's first professional co-ed technology fraternity!
            We aim to develop our members in 3 main ways: socially, professionally, and technically. Check out our
            <a href="https://ktpumd.com/">Main Site</a> if you are interested in joining us next rush!</p>
        </div>
        <div class="col-6 px-4">
            <h3>About this site:</h3>
            <p>This site is used by members and the executive board to help keep track of events, points, forms, and many other things all in one place!
            To get started, <a href="{{ url_for('users.login') }}">Log In</a> or <a href="{{ url_for('users.register') }}">Register</a>.
            </p>
        </div>
    </div>
</div>

{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-6 mx-auto shadow rounded pt-2">
            <h2>Log In</h2>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            <form action="" method="post">
                {{ form.csrf_token }}
                <div class="form-group mb-3">
                    {{ form.uid.label(class="form-control-label") }}
                    {{ form.uid(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control") }}
                </div>
                <div class="form-group mb-3">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
            <p>If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a></p>
        </div>
    </div>
</div>
{% endblock %}